// File generated by HeartPearl migration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgny9xP_riIlp-w80zn0q5VR7ix8SYwdE',
    appId: '1:592218033486:web:b83446b376d092f160a21f',
    messagingSenderId: '592218033486',
    projectId: 'tamchau-865f3',
    authDomain: 'tamchau-865f3.firebaseapp.com',
    databaseURL: 'https://tamchau-865f3-default-rtdb.firebaseio.com',
    storageBucket: 'tamchau-865f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgny9xP_riIlp-w80zn0q5VR7ix8SYwdE',
    appId: '1:592218033486:android:b83446b376d092f160a21f',
    messagingSenderId: '592218033486',
    projectId: 'tamchau-865f3',
    databaseURL: 'https://tamchau-865f3-default-rtdb.firebaseio.com',
    storageBucket: 'tamchau-865f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgny9xP_riIlp-w80zn0q5VR7ix8SYwdE',
    appId: '1:592218033486:ios:b83446b376d092f160a21f',
    messagingSenderId: '592218033486',
    projectId: 'tamchau-865f3',
    databaseURL: 'https://tamchau-865f3-default-rtdb.firebaseio.com',
    storageBucket: 'tamchau-865f3.firebasestorage.app',
    iosBundleId: 'com.heartpearl.heartpearl',
  );
}
